/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultCopilot
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  openaiApiKey: "",
  geminiApiKey: "",
  defaultModel: "gpt-5.4-mini"
};
var VaultCopilotSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("OpenAI API Key").setDesc("Enter your OpenAI API key for GPT models.").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
      this.plugin.settings.openaiApiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Gemini API Key").setDesc("Enter your Gemini API key for Google models.").addText((text) => text.setPlaceholder("AIza...").setValue(this.plugin.settings.geminiApiKey).onChange(async (value) => {
      this.plugin.settings.geminiApiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Model").setDesc("Select the model to use for chat and generation.").addDropdown((dropdown) => dropdown.addOption("gpt-5.4-mini", "GPT-5.4 Mini (OpenAI)").addOption("gpt-5.4", "GPT-5.4 (OpenAI)").addOption("gemini-3.1-flash-lite", "Gemini 3.1 Flash Lite (Google)").addOption("gemini-3.1-flash", "Gemini 3.1 Flash (Google)").addOption("gemini-3.1-pro", "Gemini 3.1 Pro (Google)").setValue(this.plugin.settings.defaultModel).onChange(async (value) => {
      this.plugin.settings.defaultModel = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/ChatPanel.ts
var import_obsidian4 = require("obsidian");

// src/LLMProvider.ts
var import_obsidian2 = require("obsidian");
var LLMProvider = class {
  constructor(settings) {
    this.settings = settings;
  }
  async generateResponse(messages) {
    const model = (this.settings.defaultModel || "gpt-5.4-mini").trim();
    if (model.startsWith("gpt")) {
      return this.callOpenAI(model, messages);
    } else if (model.startsWith("gemini")) {
      return this.callGemini(model, messages);
    } else {
      throw new Error(`Unsupported model: ${model}`);
    }
  }
  arrayBufferToBase64(buffer) {
    let binary = "";
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binary);
  }
  async callOpenAI(model, messages) {
    const apiKey = (this.settings.openaiApiKey || "").trim();
    if (!apiKey) {
      throw new Error("OpenAI API key is missing. Please set it in the plugin settings.");
    }
    const openAiMessages = messages.map((msg) => {
      if (!msg.attachments || msg.attachments.length === 0) {
        return { role: msg.role, content: msg.content };
      }
      const contentParts = [{ type: "text", text: msg.content }];
      for (const att of msg.attachments) {
        const base64 = this.arrayBufferToBase64(att.data);
        if (att.mimeType.startsWith("image/")) {
          contentParts.push({
            type: "image_url",
            image_url: { url: `data:${att.mimeType};base64,${base64}` }
          });
        } else {
          if (att.mimeType === "text/plain" || att.mimeType === "text/markdown") {
            const decoder = new TextDecoder("utf-8");
            const text = decoder.decode(att.data);
            contentParts.push({ type: "text", text: `
--- Attachment: ${att.name} ---
${text}
--- End Attachment ---
` });
          } else {
            console.warn(`OpenAI standard chat may not support native ${att.mimeType} inline.`);
          }
        }
      }
      return { role: msg.role, content: contentParts };
    });
    const request = {
      url: "https://api.openai.com/v1/chat/completions",
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model,
        messages: openAiMessages
      }),
      throw: false
    };
    try {
      const response = await (0, import_obsidian2.requestUrl)(request);
      if (response.status !== 200) {
        throw new Error(`OpenAI API error: ${response.status} - ${JSON.stringify(response.json)}`);
      }
      return response.json.choices[0].message.content;
    } catch (error) {
      console.error("LLMProvider OpenAI Error:", error);
      throw new Error(`Failed to get response from OpenAI: ${error.message}`);
    }
  }
  async callGemini(model, messages) {
    const apiKey = (this.settings.geminiApiKey || "").trim();
    if (!apiKey) {
      throw new Error("Gemini API key is missing. Please set it in the plugin settings.");
    }
    const geminiContents = messages.filter((msg) => msg.role !== "system").map((msg) => {
      const parts = [];
      if (msg.content) {
        parts.push({ text: msg.content });
      }
      if (msg.attachments) {
        for (const att of msg.attachments) {
          const base64 = this.arrayBufferToBase64(att.data);
          if (att.mimeType === "text/plain" || att.mimeType === "text/markdown") {
            const decoder = new TextDecoder("utf-8");
            const text = decoder.decode(att.data);
            parts.push({ text: `
--- Attachment: ${att.name} ---
${text}
--- End Attachment ---
` });
          } else {
            parts.push({
              inlineData: {
                mimeType: att.mimeType,
                data: base64
              }
            });
          }
        }
      }
      return {
        role: msg.role === "assistant" ? "model" : "user",
        parts
      };
    });
    const systemMessages = messages.filter((msg) => msg.role === "system");
    const systemInstruction = systemMessages.length > 0 ? { parts: [{ text: systemMessages.map((m) => m.content).join("\n") }] } : void 0;
    const requestBody = {
      contents: geminiContents
    };
    if (systemInstruction) {
      requestBody.systemInstruction = systemInstruction;
    }
    const request = {
      url: `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(requestBody),
      throw: false
    };
    try {
      const response = await (0, import_obsidian2.requestUrl)(request);
      if (response.status !== 200) {
        throw new Error(`Gemini API error: ${response.status} - ${JSON.stringify(response.json)}`);
      }
      if (response.json.candidates && response.json.candidates.length > 0) {
        return response.json.candidates[0].content.parts[0].text;
      }
      throw new Error("No response candidates returned from Gemini.");
    } catch (error) {
      console.error("LLMProvider Gemini Error:", error);
      throw new Error(`Failed to get response from Gemini: ${error.message}`);
    }
  }
};

// src/PDFHandler.ts
var PDFHandler = class {
  /**
   * Reads an existing vault file as an ArrayBuffer using Obsidian's API.
   */
  static async readVaultFile(app, file) {
    const arrayBuffer = await app.vault.readBinary(file);
    let mimeType = "application/octet-stream";
    const extension = file.extension.toLowerCase();
    if (extension === "pdf")
      mimeType = "application/pdf";
    else if (extension === "md")
      mimeType = "text/markdown";
    else if (extension === "txt")
      mimeType = "text/plain";
    else if (["png", "jpg", "jpeg", "gif", "webp"].includes(extension))
      mimeType = `image/${extension === "jpg" ? "jpeg" : extension}`;
    return {
      name: file.name,
      mimeType,
      data: arrayBuffer
    };
  }
  /**
   * Opens a native file picker dialogue and reads the selected file as an ArrayBuffer.
   * This works on mobile (iOS/Android) and desktop by relying on standard web APIs
   * and avoiding any `fs` or `file.path` dependencies.
   */
  static async selectAndReadFile() {
    return new Promise((resolve) => {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = ".pdf,.md,.txt,image/*";
      input.multiple = false;
      input.onchange = async (e) => {
        const target = e.target;
        if (!target.files || target.files.length === 0) {
          resolve(null);
          return;
        }
        const file = target.files[0];
        const reader = new FileReader();
        reader.onload = async (e2) => {
          var _a;
          const arrayBuffer = (_a = e2.target) == null ? void 0 : _a.result;
          let mimeType = file.type;
          if (!mimeType) {
            if (file.name.endsWith(".pdf"))
              mimeType = "application/pdf";
            else if (file.name.endsWith(".md"))
              mimeType = "text/markdown";
            else if (file.name.endsWith(".txt"))
              mimeType = "text/plain";
            else
              mimeType = "application/octet-stream";
          }
          resolve({
            name: file.name,
            mimeType,
            data: arrayBuffer
          });
        };
        reader.onerror = () => {
          console.error("Failed to read file");
          resolve(null);
        };
        reader.readAsArrayBuffer(file);
      };
      input.click();
    });
  }
};

// src/PromptLibrary.ts
var PromptLibrary = class {
  // For Phase 1, we hardcode some useful defaults.
  // Later phases could load this from settings or a specific vault note.
  static getPrompts() {
    return [
      {
        id: "summarize",
        label: "/summarize",
        prompt: "Summarize the provided content into key bullet points."
      },
      {
        id: "extract-concepts",
        label: "/extract-concepts",
        prompt: "Extract the core medical/scientific concepts from this text."
      },
      {
        id: "explain",
        label: "/explain",
        prompt: "Explain this concept simply as if to a medical student."
      }
    ];
  }
};

// src/DiffPreview.ts
var import_obsidian3 = require("obsidian");
var DiffPreview = class extends import_obsidian3.Modal {
  constructor(app, contentToSave, onApprove) {
    super(app);
    this.contentToSave = contentToSave;
    this.onApprove = onApprove;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Preview Changes");
    contentEl.createEl("p", { text: "Review the content below before saving it to your vault." });
    const textArea = contentEl.createEl("textarea", {
      text: this.contentToSave,
      attr: { style: "width: 100%; height: 300px; resize: vertical; margin-bottom: 15px; font-family: monospace;" }
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
      this.close();
    })).addButton((btn) => btn.setButtonText("Approve & Save").setCta().onClick(async () => {
      const finalContent = textArea.value;
      this.close();
      try {
        await this.onApprove(finalContent);
      } catch (e) {
        new import_obsidian3.Notice(`Failed to save: ${e.message}`);
      }
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ChatPanel.ts
var CHAT_VIEW_TYPE = "vault-copilot-chat-view";
var ChatPanel = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.attachments = [];
    this.plugin = plugin;
    this.llmProvider = new LLMProvider(plugin.settings);
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Vault Copilot Chat";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    this.renderUI();
  }
  async onClose() {
  }
  renderUI() {
    const container = this.containerEl.children[1];
    container.empty();
    const wrapper = container.createDiv({ cls: "vault-copilot-chat-container" });
    const messagesDiv = wrapper.createDiv({ cls: "vault-copilot-messages" });
    this.renderMessages(messagesDiv);
    const inputContainer = wrapper.createDiv({ cls: "vault-copilot-input-container" });
    const filesDiv = inputContainer.createDiv({ cls: "vault-copilot-file-list" });
    this.renderAttachments(filesDiv);
    const inputRow = inputContainer.createDiv({ cls: "vault-copilot-input-row" });
    const textArea = inputRow.createEl("textarea", { cls: "vault-copilot-textarea" });
    textArea.placeholder = "Type your message or type / for prompts...";
    textArea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage(textArea, messagesDiv, filesDiv);
      }
    });
    textArea.addEventListener("input", () => {
      if (textArea.value.endsWith("/")) {
      }
    });
    const attachBtn = inputRow.createEl("button", { text: "\u{1F4CE}" });
    attachBtn.onclick = async () => {
      const file = await PDFHandler.selectAndReadFile();
      if (file) {
        this.attachments.push(file);
        this.renderAttachments(filesDiv);
      }
    };
    const sendBtn = inputRow.createEl("button", { text: "Send" });
    sendBtn.onclick = () => this.sendMessage(textArea, messagesDiv, filesDiv);
  }
  renderAttachments(container) {
    container.empty();
    for (let i = 0; i < this.attachments.length; i++) {
      const att = this.attachments[i];
      const tag = container.createDiv({ cls: "vault-copilot-file-tag" });
      tag.createSpan({ text: att.name });
      const removeBtn = tag.createSpan({ cls: "vault-copilot-remove-file", text: " \u2715" });
      removeBtn.onclick = () => {
        this.attachments.splice(i, 1);
        this.renderAttachments(container);
      };
    }
  }
  renderMessages(container) {
    container.empty();
    for (const msg of this.messages) {
      const msgDiv = container.createDiv({ cls: `vault-copilot-message ${msg.role}` });
      if (msg.role === "user" && msg.attachments && msg.attachments.length > 0) {
        const attDiv = msgDiv.createDiv();
        attDiv.style.fontStyle = "italic";
        attDiv.style.fontSize = "0.8em";
        attDiv.style.marginBottom = "5px";
        attDiv.textContent = `Attached: ${msg.attachments.map((a) => a.name).join(", ")}`;
      }
      const contentDiv = msgDiv.createDiv();
      if (msg.role === "user") {
        contentDiv.textContent = msg.content;
      } else {
        import_obsidian4.MarkdownRenderer.renderMarkdown(msg.content, contentDiv, "", this.plugin);
        const actionsDiv = msgDiv.createDiv({ cls: "vault-copilot-message-actions" });
        actionsDiv.style.marginTop = "10px";
        actionsDiv.style.display = "flex";
        actionsDiv.style.justifyContent = "flex-end";
        const saveBtn = actionsDiv.createEl("button", { text: "Save to Note" });
        saveBtn.onclick = () => {
          new DiffPreview(this.plugin.app, msg.content, async (finalContent) => {
            await this.createNewNoteWithContent(finalContent);
          }).open();
        };
      }
    }
    container.scrollTo(0, container.scrollHeight);
  }
  async createNewNoteWithContent(content) {
    const title = `Copilot Note ${window.moment().format("YYYY-MM-DD HH-mm-ss")}`;
    const newFile = await this.plugin.app.vault.create(`${title}.md`, content);
    const leaf = this.plugin.app.workspace.getLeaf(true);
    await leaf.openFile(newFile);
    new import_obsidian4.Notice(`Saved to ${title}`);
  }
  async sendMessage(textArea, messagesDiv, filesDiv) {
    let text = textArea.value.trim();
    const prompts = PromptLibrary.getPrompts();
    for (const p of prompts) {
      if (text.startsWith(p.label)) {
        text = text.replace(p.label, p.prompt);
        break;
      }
    }
    if (!text && this.attachments.length === 0)
      return;
    const userMsg = {
      role: "user",
      content: text,
      attachments: [...this.attachments]
    };
    this.messages.push(userMsg);
    textArea.value = "";
    this.attachments = [];
    this.renderAttachments(filesDiv);
    this.renderMessages(messagesDiv);
    const loadingMsg = { role: "assistant", content: "..." };
    this.messages.push(loadingMsg);
    this.renderMessages(messagesDiv);
    try {
      this.llmProvider.settings = this.plugin.settings;
      const response = await this.llmProvider.generateResponse(this.messages.slice(0, -1));
      this.messages.pop();
      this.messages.push({ role: "assistant", content: response });
    } catch (error) {
      this.messages.pop();
      this.messages.push({ role: "assistant", content: `**Error:** ${error.message}` });
    }
    this.renderMessages(messagesDiv);
  }
};

// main.ts
var VaultCopilot = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new VaultCopilotSettingTab(this.app, this));
    this.registerView(
      CHAT_VIEW_TYPE,
      (leaf) => new ChatPanel(leaf, this)
    );
    this.addRibbonIcon("message-circle", "Open Vault Copilot", () => {
      this.activateChatView();
    });
    this.addCommand({
      id: "create-note-from-lecture",
      name: "Create Note from Lecture",
      callback: () => {
        this.createNoteFromLecture();
      }
    });
  }
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(CHAT_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async createNoteFromLecture() {
    const file = await PDFHandler.selectAndReadFile();
    if (!file) {
      new import_obsidian5.Notice("No file selected.");
      return;
    }
    new import_obsidian5.Notice(`Processing ${file.name}...`);
    try {
      const llm = new LLMProvider(this.settings);
      const promptMsg = {
        role: "user",
        content: "Extract the core concepts and summarize the key points from this lecture material.",
        attachments: [file]
      };
      const response = await llm.generateResponse([promptMsg]);
      new DiffPreview(this.app, response, async (finalContent) => {
        const title = `Lecture Note ${window.moment().format("YYYY-MM-DD HH-mm-ss")}`;
        const newFile = await this.app.vault.create(`${title}.md`, finalContent);
        const leaf = this.app.workspace.getLeaf(true);
        await leaf.openFile(newFile);
        new import_obsidian5.Notice(`Created note: ${title}`);
      }).open();
    } catch (error) {
      console.error("Create Note from Lecture failed", error);
      new import_obsidian5.Notice(`Error: ${error.message}`);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
