import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const prod = (process.argv[2] === "production");

// Output destination: scratch test vault plugin folder.
// Change this path if you switch to a different vault for testing.
const vaultPluginDir = String.raw`C:\Users\X!-Carbon\Documents\Obsidian Vault\.obsidian\plugins\vault-copilot`;

const context = await esbuild.context({
	banner: {
		js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nif you want to view the source, please visit the github repository of this plugin\n*/',
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(vaultPluginDir, "main.js"),
});

if (prod) {
	await context.rebuild();

	// Copy the other files Obsidian needs alongside main.js.
	fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
	fs.copyFileSync("styles.css",    path.join(vaultPluginDir, "styles.css"));
	console.log(`✅ Build copied to: ${vaultPluginDir}`);

	process.exit(0);
} else {
	// Watch mode: main.js is written directly to the vault on every rebuild.
	// manifest.json and styles.css rarely change — copy them once at startup.
	fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
	fs.copyFileSync("styles.css",    path.join(vaultPluginDir, "styles.css"));
	console.log(`👀 Watching — output: ${vaultPluginDir}`);
	await context.watch();
}
